
name: Publish to Google Artifact Registry

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to GAR
        uses: docker/login-action@v1
        with:
          registry: europe-west2-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_CREDENTIALS }}
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: europe-west2-docker.pkg.dev/comp3000-air-quality/comp3000-docker/predictions:latest
